// doc/main/linter/components/code-example.vue
<template>
  <div class="code-container">
    <h4 className='code-header'>
      {{ title }}
    </h4>
    <div className='code-content'>
      <slot></slot>
    </div>
    <div class="code-footer">
      <div class="code-btn-container"  :class="[showOption ? 'expand' : 'close']" @click="btnClick">
        <div class='show-code'>
          <IconChevronUp v-if="!showOption"></IconChevronUp>
          <IconChevronDown v-else></IconChevronDown>查看代码</div>
      </div>
      <v-md-preview class="markdown code-block-box" :text="code" :style="{display: showOption ? 'block' : 'none'}"></v-md-preview >
    </div>
  </div>
</template>

<script>
import { IconChevronUp, IconChevronDown } from '@opentiny/vue-icon'

export default {
  name: 'CodeExample',
  components: {
    IconChevronUp: IconChevronUp(),
    IconChevronDown: IconChevronDown()
  },
  props: {
    code: {
      type: String
    },
    title: {
      type: String
    },
  },
  data(){
    return {
      showOption: false
    }
  },
  methods: {
    btnClick(){
      this.showOption = !this.showOption
    }
  }
}
</script>

// doc/Example/MarkdownPage/mediaScreen/CodeExample.jsx
import React, { useState } from 'react';
import MarkdownElement from '../../../components/MarkdownElement';

export default function CodeExample(props) {
  const { code, children, title, className } = props;
  const [showOption, setShowOption] = useState(false);

  const btnClick = () => {
    setShowOption(!showOption);
  };

  const text = `\`\`\`javascript
${code}
  \`\`\``;

  return (
    <div className={`codeContainer ic-example-explore ${className}`}>
      <h4 className='codeHeader'>
        {title}
      </h4>
      <div className='codeContent'>
        {children}
      </div>
      <div className={'codeFooter'}>
        <div className={`codeBtnContainer ${showOption ? 'expand' : 'close'}`} onClick={btnClick}>
          <div title={'查看代码'}>
            <div className={`codeBtn ${showOption ? 'expand' : 'close'}`}></div>
            <div className='showCode'>查看代码</div>
          </div>
        </div>
        <MarkdownElement
          className="code-block-box"
          text={text}
          style={{ display: showOption ? 'block' : 'none' }}
        />
      </div>
    </div>
  );
}
